//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.07 at 10:28:20 PM BDT 
//


package org.bb.cbs.soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bb.cbs.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListEmployees_QNAME = new QName("http://soap.cbs.bb.org/", "listEmployees");
    private final static QName _ListEmployeesResponse_QNAME = new QName("http://soap.cbs.bb.org/", "listEmployeesResponse");
    private final static QName _UpdateEmployee_QNAME = new QName("http://soap.cbs.bb.org/", "updateEmployee");
    private final static QName _UpdateEmployeeResponse_QNAME = new QName("http://soap.cbs.bb.org/", "updateEmployeeResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bb.cbs.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListEmployees }
     * 
     */
    public ListEmployees createListEmployees() {
        return new ListEmployees();
    }

    /**
     * Create an instance of {@link ListEmployeesResponse }
     * 
     */
    public ListEmployeesResponse createListEmployeesResponse() {
        return new ListEmployeesResponse();
    }

    /**
     * Create an instance of {@link UpdateEmployee }
     * 
     */
    public UpdateEmployee createUpdateEmployee() {
        return new UpdateEmployee();
    }

    /**
     * Create an instance of {@link UpdateEmployeeResponse }
     * 
     */
    public UpdateEmployeeResponse createUpdateEmployeeResponse() {
        return new UpdateEmployeeResponse();
    }

    /**
     * Create an instance of {@link EmployeeData }
     * 
     */
    public EmployeeData createEmployeeData() {
        return new EmployeeData();
    }

    /**
     * Create an instance of {@link BaseData }
     * 
     */
    public BaseData createBaseData() {
        return new BaseData();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListEmployees }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://soap.cbs.bb.org/", name = "listEmployees")
    public JAXBElement<ListEmployees> createListEmployees(ListEmployees value) {
        return new JAXBElement<ListEmployees>(_ListEmployees_QNAME, ListEmployees.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListEmployeesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://soap.cbs.bb.org/", name = "listEmployeesResponse")
    public JAXBElement<ListEmployeesResponse> createListEmployeesResponse(ListEmployeesResponse value) {
        return new JAXBElement<ListEmployeesResponse>(_ListEmployeesResponse_QNAME, ListEmployeesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateEmployee }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://soap.cbs.bb.org/", name = "updateEmployee")
    public JAXBElement<UpdateEmployee> createUpdateEmployee(UpdateEmployee value) {
        return new JAXBElement<UpdateEmployee>(_UpdateEmployee_QNAME, UpdateEmployee.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateEmployeeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://soap.cbs.bb.org/", name = "updateEmployeeResponse")
    public JAXBElement<UpdateEmployeeResponse> createUpdateEmployeeResponse(UpdateEmployeeResponse value) {
        return new JAXBElement<UpdateEmployeeResponse>(_UpdateEmployeeResponse_QNAME, UpdateEmployeeResponse.class, null, value);
    }

}
